### ISSUE TITLE
Illegal division by zero

### ISSUE THREAD

**Issue by fridobox** [Libriotech/koha-plugin-stateofgdpr#1]
Hi,

Great plugin :+1: 

I've an error with UNIMARC demo database :

Template process failed: undef error - Illegal division by zero at /mnt/git/koha-plugin-stateofgdpr/Koha/Plugin/No/Libriotech/StateOfGDPR/main.tt line 108.

Best regards

**Comment by MagnusEnger** [comment]
Thanks! And thanks for reporting the problem. 

Guess this does not work well if old_issues = 0...
```
[% old_issues_anonymized * 100 / old_issues %]
```

**Comment by fridobox** [comment]
It's the demo effect.
I have tested with the sandbox demo dump which is not a "real" database ;)
